### ISSUE TITLE
MKVToolnix 70 for Windows 7

### ISSUE THREAD

**Issue by malvarenga123** [jpsdr/MKVToolnix-Windows-7#1]
Hi @jpsdr, thank you for your W7 build. Do you plan to release a new one for MKVToolnix 70.0?

**Comment by jpsdr** [comment]
I don't have access to a Linux PC often, and the one who realy begun this has made one : https://forum.videohelp.com/threads/405407-NON-OFFICIAL-Windows-builds-of-MKVtoolnix-do-they-exist?p=2665052&viewfull=1#post2665052

**Comment by jpsdr** [comment]
The one who begun this made a 71.0.0 release : https://forum.videohelp.com/threads/405407-NON-OFFICIAL-Windows-builds-of-MKVtoolnix/page3#post2669522
I suggest you check the place time to time.
