### ISSUE TITLE
removed support for Qt 5 - possible fix

### ISSUE THREAD

**Issue by ask2018** [jpsdr/MKVToolnix-Windows-7#2]
Hello jpsdr and thanks for your work  on Win7 compatible builds of MKVToolnix.
I'm reacting here on what you have written on Doom9 forums two days ago about the last commit by Mosu and removed QT5 support.
Check out this project. It's another QT program where somebody made it work with QT6 on Win7. Maybe it might be helpful for you to continue with the updates for MKVToolnix
https://www.patreon.com/posts/rpcs3-0-0-29-qt-88446670
https://github.com/okt04175/rpcs3-qt64
https://github.com/okt04175/api-ms-win-core-synch-Win7

**Comment by jpsdr** [comment]
Hello.
Sorry, but i absolutely don't have the knowledge of how i can eventualy do such a thing.
I'm barely able to build the programm following step by strep the instructions.
This is totaly out of my skills.

**Comment by ask2018** [comment]
I see and understand. Could you suggest this to the other guy "autodidact" @ videohelp forum? I see you are talking there as well. I don't have account there and there is some antispam protection on account creation,  I don't want to fight atm. just to say single sentence.

**Comment by ask2018** [comment]
Thank you for reposting the info @ videohelp forums. I did few tests and here are the results. Feel free to repost the info there.

If I try to copy the 2 dlls from this project https://github.com/okt04175/api-ms-win-core-synch-Win7 to MKVToolnix folder, then I can run official MKVToolnix 70 and 71 but without the GUI process (than means I can run mkvextract.exe, mkvinfo.exe, mkvmerge.exe and mkvpropedit.exe - but mkvtoolnix-gui.exe fails with another missing fuction - VXKex (https://github.com/vxiiduu/VxKex) fix that partially, but it fails on another missing function later ).

Version 72+ I cannot run even with the dlls.

Version 70 and 71 seems to be using QT 6.3.1
Version 72 seems to be using QT 6.4.0

Author of the "api-ms-win-core-synch-Win7" fixed MKVToolnix 77 (again without the GUI) on this project and that seems to be using QT 6.5.0
https://www.patreon.com/posts/win7-fix-for-01-79541597

So I guess we need @okt04175 help if he is interested and able to update his project to fully support MKVToolnix on Win7 systems.
