### ISSUE TITLE
Window is too large for low resolution

### ISSUE THREAD

**Issue by sergeevabc** [jpsdr/MKVToolnix-Windows-7#3]
Windows 7 x64, MKVToolnix QT5 84.0.10.

I have 1024x768 here.

![2024-0513-0234 resolution 1024x768](https://github.com/jpsdr/MKVToolnix-Windows-7/assets/373718/a0e870cd-ee77-4e8c-8648-9019cf1ba021)

And the app's window is too large upon launch with no intuitive way to scale it.

 ![2024-0513-0235 mkvtoolnix-gui](https://github.com/jpsdr/MKVToolnix-Windows-7/assets/373718/829b85f1-9cf1-4dfa-ac31-e3a6e178063b)

**Comment by jpsdr** [comment]
Sorry, but i'm just barrely able to make a build, i absolutely don't have the knowledge to make any adjustment.
